" === General ===
set nocompatible
set encoding=utf-8
set fileencoding=utf-8
set backspace=indent,eol,start
set hidden
set mouse=a
set clipboard=unnamedplus
set wildmenu
set wildmode=longest:full,full
set laststatus=2
set ruler
set showcmd
set showmode

" === Line Numbers ===
set number
"set relativenumber

" === Tabs & Indentation ===
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smartindent

" === Search ===
set incsearch
set hlsearch
set ignorecase
set smartcase

" === Visual ===
if has('termguicolors')
    set termguicolors
endif
set background=dark
set runtimepath^=~/.config/vim
syntax on
colorscheme minimal
set cursorline
set scrolloff=8
set sidescrolloff=8
set signcolumn=yes
set wrap
set linebreak

" === Performance ===
set lazyredraw
set ttyfast
set updatetime=300

" === Splits ===
set splitbelow
set splitright

" === No Backup Clutter ===
set nobackup
set nowritebackup
set noswapfile

" === Ctrl+HJKL Navigation in Insert Mode ===
inoremap <C-h> <Left>
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-l> <Right>

" === Leader Key ===
let mapleader = " "

" === Handy Mappings ===
nnoremap <leader>w :w<CR>
nnoremap <leader>q :q<CR>
nnoremap <leader>/ :nohlsearch<CR>
